name: Test Mock Pipeline

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test-mock-pipeline:
    # Run on PRs targeting main branch'
    if: github.base_ref == 'main'
    uses: ./.github/workflows/reusable-mock-integration-tests.yml
    secrets: inherit
    with:
      python-version: '3.10'
