name: Integration Tests (workers, tools, agents, etc.)

on:
  pull_request:
    types: [opened, edited, synchronize, labeled]

jobs:
  test-mock-pipelines:
    # Run on PRs targeting main branch'
    if: github.base_ref == 'main'
    uses: ./.github/workflows/reusable-mock-integration-tests.yml
    with:
      python-version: '3.10'

  test-pipelines:
    # Only run on PRs targeting main labeled with 'live-integration-tests'
    if: github.base_ref == 'main' && github.event.label.name == 'live-integration-tests'
    uses: ./.github/workflows/reusable-live-integration-tests.yml
    with:
      python-version: '3.10'
    continue-on-error: true
